apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-api
  labels:
    app: fraud-api

spec:
  replicas: 1   # 🔥 IMPORTANT (only 1 pod)

  selector:
    matchLabels:
      app: fraud-api

  template:
    metadata:
      labels:
        app: fraud-api

    spec:
      containers:
        - name: fraud-api
          image: karthikeyajeshwanth/fraud-detection-model:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 5
