apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-api
  labels:
    app: fraud-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: fraud-api

  template:
    metadata:
      labels:
        app: fraud-api

    spec:
      containers:
        - name: fraud-api
          image: karthikeyajeshwanth/fraud-detection-model:latest
          ports:
            - containerPort: 5000

          # 🔥 LIVENESS PROBE
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3

          # 🔥 READINESS PROBE
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3