apiVersion: v1
kind: Service
metadata:
  name: fraud-service
spec:
  type: NodePort
  selector:
    app: fraud-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
